name: EIE101 Feed Update
on:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours
  workflow_dispatch: # Manual trigger

jobs:
  update-readme-with-blog:
    name: Sync Blogspot Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull EIE101 RSS
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://eie101.blogspot.com/feeds/posts/default?alt=rss"
          max_post_count: 5
          template: "$newline >_ [$title]($url)"
          committer_username: "afnnan-bot"
          committer_email: "afnnan.dev@gmail.com"
