name: EIE101 Feed Update
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Sync Blogspot Data
    runs-on: ubuntu-latest
    steps:
- name: Pull EIE101 RSS
  uses: gautamkrishnar/blog-post-workflow@v1
  continue-on-error: true
  with:
    feed_list: "https://eie101.blogspot.com/"
    max_post_count: 5
    template: "$newline >_ [$title]($url)"
    committer_username: "afnnan-bot"
    committer_email: "afnnan.dev@gmail.com"
